server:
  port: 7112
  max-http-header-size: 10MB
  servlet:
    context-path: /catalogo
spring:
  application:
    name: catalogo-api
  mvc:
    servlet:
      path: /api/v1
      
logging:
  level:
    com: INFO
