server:
  port: 7112
  max-http-header-size: 10MB
  servlet:
    context-path: /catalogo
spring:
  application:
    name: catalogo-api
  mvc:
    servlet:
      path: /api/v1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show-sql: true
      
logging:
  level:
    org:
      hibernate: 
        SQL:  DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO
  config: classpath:logback-dev.xml
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss:SSS} %t %c{2}:%L - %m%n'