api:
  access:
    user: us3r-cat4log
    password: cGFzJGM0dDIyIQ==
  datasource:
    tel:
      prefijo:  '72'
      configuration:
        hikari:
          maximum-pool-size: 8
      driver:
        class: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        enable_lazy_load_no_trans: true
        format_sql: false
        show_sql: false
      jdbcUrl: jdbc:sqlserver://MSSQLCDEV.truper.com.mx\DEV;databaseName=tel
      package: 
        entities: com.truper.catalogo.tel.entities
        base: com.truper.catalogo.tel
      password: t3lw3b2019
      url: jdbc:sqlserver://172.18.2.14:1433;databaseName=tel
      username: telweb
    sae:
      configuracion:
        hikari:
          maximun-pool-size: 8
      driver:
        class: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        enable_lazy_load_no_trans: true
        format_sql: false
        show_sql: false
      jdbcUrl: jdbc:sqlserver://;serverName=172.20.5.157;databaseName=SAE_NACIONALES;encrypt=false;trustServerCertificate=false;
      package: 
        entities: com.truper.saen.commons
        base: com.truper.catalogo.saen
      password: truper2022
      url: jdbc:sqlserver://;serverName=172.20.5.157;databaseName=SAE_NACIONALES;encrypt=false;trustServerCertificate=false;
      username: APP_SAEN
  crones:
    listaCentros: '0 0 2 * * ?' 
logging:
  level:
    org:
      hibernate: 
        SQL:  INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework: INFO
  config: classpath:logback-prod.xml
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss:SSS} %t %c{2}:%L - %m%n'